kind: Service
apiVersion: v1
metadata:
  name: my-msgs-service
spec:
  ports:
    - name: read
      port: 5000
      targetPort: 5000
    - name: disp
      port: 5010
      targetPort: 5010
  selector:
    app: my-msgs
  type: LoadBalancer
